// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEhqM5KjIqSWFJx_sUbozulv4h6CN-jtg',
    appId: '1:124357149675:android:344a0063f7468cdd448fae',
    messagingSenderId: '124357149675',
    projectId: 'flowa-4fca9',
    storageBucket: 'flowa-4fca9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuhlxgf4riw8TjnmOi2-Wv55K8R6jjko',
    appId: '1:124357149675:ios:e9241c5a34e11542448fae',
    messagingSenderId: '124357149675',
    projectId: 'flowa-4fca9',
    storageBucket: 'flowa-4fca9.firebasestorage.app',
    androidClientId: '124357149675-gputtkb4usjco6lvm1cjdlhp9feno556.apps.googleusercontent.com',
    iosClientId: '124357149675-edhlldm2p5b18afh3gad6dkjjo082k39.apps.googleusercontent.com',
    iosBundleId: 'com.flowa.flowa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhqM5KjIqSWFJx_sUbozulv4h6CN-jtg',
    appId: '1:124357149675:web:344a0063f7468cdd448fae',
    messagingSenderId: '124357149675',
    projectId: 'flowa-4fca9',
    authDomain: 'flowa-4fca9.firebaseapp.com',
    storageBucket: 'flowa-4fca9.firebasestorage.app',
  );
}
