import 'package:flutter/material.dart';

enum RewardType { points, freeze, booster, coins, chest }

class DailyStreakReward {
  final int day;
  final String title;
  final String description;
  final RewardType type;
  final int points;
  final int coins;
  final int freezes;
  final String icon;
  final Color color;

  const DailyStreakReward({
    required this.day,
    required this.title,
    required this.description,
    required this.type,
    this.points = 0,
    this.coins = 0,
    this.freezes = 0,
    required this.icon,
    required this.color,
  });

  static List<DailyStreakReward> getAllMonthRewards() {
    return [
      const DailyStreakReward(
        day: 1,
        title: '+10 PTS',
        description: 'Boshlang‘ich energiya',
        type: RewardType.points,
        points: 10,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 2,
        title: 'Muzlatgich',
        description: 'Odatni saqlash qalqoni',
        type: RewardType.freeze,
        freezes: 1,
        icon: '❄️',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 3,
        title: '+30 PTS',
        description: 'Faollik bonusi',
        type: RewardType.points,
        points: 30,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 4,
        title: '2x Buster',
        description: '2 barobar tez ochko yig‘ish',
        type: RewardType.booster,
        icon: '🚀',
        color: Color(0xFFFF9900),
      ),
      const DailyStreakReward(
        day: 5,
        title: '+10 Tanga',
        description: 'Fenix Coin xazinasi',
        type: RewardType.coins,
        coins: 10,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 6,
        title: '+50 PTS',
        description: 'Super motivatsiya',
        type: RewardType.points,
        points: 50,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 7,
        title: 'Haftalik Sandiq',
        description: '+100 PTS & +20 Tanga',
        type: RewardType.chest,
        points: 100,
        coins: 20,
        icon: '🎁',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 8,
        title: '+20 PTS',
        description: '2-hafta starti',
        type: RewardType.points,
        points: 20,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 9,
        title: 'Muzlatgich',
        description: 'Zaxira himoya',
        type: RewardType.freeze,
        freezes: 1,
        icon: '❄️',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 10,
        title: '+25 Tanga',
        description: 'Fenix Coin bonusi',
        type: RewardType.coins,
        coins: 25,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 11,
        title: '2x Buster',
        description: 'Eksklyuziv buster',
        type: RewardType.booster,
        icon: '🚀',
        color: Color(0xFFFF9900),
      ),
      const DailyStreakReward(
        day: 12,
        title: '+50 PTS',
        description: 'Energiya oqimi',
        type: RewardType.points,
        points: 50,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 13,
        title: 'Muzlatgich',
        description: 'Streak qalqoni',
        type: RewardType.freeze,
        freezes: 1,
        icon: '❄️',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 14,
        title: 'Oltin Sandiq',
        description: '+200 PTS & +50 Tanga',
        type: RewardType.chest,
        points: 200,
        coins: 50,
        icon: '👑',
        color: Color(0xFFFFD700),
      ),
      const DailyStreakReward(
        day: 15,
        title: '+30 Tanga',
        description: 'Yarim oylik g‘alaba',
        type: RewardType.coins,
        coins: 30,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 16,
        title: '+60 PTS',
        description: 'Kuchli iroda',
        type: RewardType.points,
        points: 60,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 17,
        title: 'Muzlatgich',
        description: 'Favqulodda himoya',
        type: RewardType.freeze,
        freezes: 1,
        icon: '❄️',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 18,
        title: '2x Buster',
        description: 'Mega buster',
        type: RewardType.booster,
        icon: '🚀',
        color: Color(0xFFFF9900),
      ),
      const DailyStreakReward(
        day: 19,
        title: '+40 Tanga',
        description: 'Fenix tangalari',
        type: RewardType.coins,
        coins: 40,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 20,
        title: '+80 PTS',
        description: 'Temuriy shijoat',
        type: RewardType.points,
        points: 80,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 21,
        title: 'Platina Sandiq',
        description: '+300 PTS & +100 Tanga',
        type: RewardType.chest,
        points: 300,
        coins: 100,
        icon: '💎',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 22,
        title: '+50 Tanga',
        description: 'Fenix boyligi',
        type: RewardType.coins,
        coins: 50,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 23,
        title: 'Muzlatgich',
        description: 'Muzlatgich qalqoni',
        type: RewardType.freeze,
        freezes: 1,
        icon: '❄️',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 24,
        title: '2x Buster',
        description: 'Super quvvat',
        type: RewardType.booster,
        icon: '🚀',
        color: Color(0xFFFF9900),
      ),
      const DailyStreakReward(
        day: 25,
        title: '+100 PTS',
        description: 'Masterlik yo‘li',
        type: RewardType.points,
        points: 100,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 26,
        title: '+60 Tanga',
        description: 'Oltin zaxira',
        type: RewardType.coins,
        coins: 60,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 27,
        title: 'Muzlatgich',
        description: 'Odat himoyachisi',
        type: RewardType.freeze,
        freezes: 1,
        icon: '❄️',
        color: Color(0xFF3B9BFF),
      ),
      const DailyStreakReward(
        day: 28,
        title: '+150 PTS',
        description: 'Afsonaviy oqim',
        type: RewardType.points,
        points: 150,
        icon: '⚡',
        color: Color(0xFF5BC8FA),
      ),
      const DailyStreakReward(
        day: 29,
        title: '+80 Tanga',
        description: 'Elita sovg‘asi',
        type: RewardType.coins,
        coins: 80,
        icon: '🪙',
        color: Color(0xFFFFB703),
      ),
      const DailyStreakReward(
        day: 30,
        title: 'FENIX SANDIQ 🔥',
        description: '+500 PTS, +200 Tanga, 2 Muzlatgich',
        type: RewardType.chest,
        points: 500,
        coins: 200,
        freezes: 2,
        icon: '🔥',
        color: Color(0xFFFF0055),
      ),
      const DailyStreakReward(
        day: 31,
        title: 'AFSONAVIY XAZINA 👑',
        description: '+1000 PTS & +300 Tanga',
        type: RewardType.chest,
        points: 1000,
        coins: 300,
        icon: '🏆',
        color: Color(0xFFFFD700),
      ),
    ];
  }
}
